//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public string ChildId { get; set; }
        public string ChildName { get; set; }
        public int ChildClass { get; set; }
        public string ChildGroup { get; set; }
    }
}
