//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAlerts
    {
        public string ChildId { get; set; }
        public System.TimeSpan AvgTime { get; set; }
        public bool IsComing_ { get; set; }
        public bool IsMissing_ { get; set; }
    }
}
